/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chasenoel.directorystructuretemplates;

import java.io.File;
import javax.swing.JFileChooser;
import org.openide.util.NbPreferences;

final class CustomDirectoryStructurePanel extends javax.swing.JPanel {

    private final CustomDirectoryStructureOptionsPanelController controller;

    CustomDirectoryStructurePanel(CustomDirectoryStructureOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zipFileLocationChooser = new javax.swing.JFileChooser();
        zipFileLocationLabel = new javax.swing.JLabel();
        zipFileLocation = new javax.swing.JTextField();
        zipFileLocationButton = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(zipFileLocationLabel, org.openide.util.NbBundle.getMessage(CustomDirectoryStructurePanel.class, "CustomDirectoryStructurePanel.zipFileLocationLabel.text")); // NOI18N

        zipFileLocation.setText(org.openide.util.NbBundle.getMessage(CustomDirectoryStructurePanel.class, "CustomDirectoryStructurePanel.zipFileLocation.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(zipFileLocationButton, org.openide.util.NbBundle.getMessage(CustomDirectoryStructurePanel.class, "CustomDirectoryStructurePanel.zipFileLocationButton.text")); // NOI18N
        zipFileLocationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zipFileLocationButtonMouseClicked(evt);
            }
        });
        zipFileLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipFileLocationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(zipFileLocationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zipFileLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zipFileLocationButton)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipFileLocationLabel)
                    .addComponent(zipFileLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipFileLocationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(222, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void zipFileLocationButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zipFileLocationButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_zipFileLocationButtonMouseClicked

    private void zipFileLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipFileLocationButtonActionPerformed
        int returnVal = zipFileLocationChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = zipFileLocationChooser.getSelectedFile();
            zipFileLocation.setText(file.getAbsolutePath());
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_zipFileLocationButtonActionPerformed

    void load() {
        // TODO read settings and initialize GUI
        // Example:        
        // someCheckBox.setSelected(Preferences.userNodeForPackage(CustomDirectoryStructurePanel.class).getBoolean("someFlag", false));
        // or for org.openide.util with API spec. version >= 7.4:
        zipFileLocation.setText(NbPreferences.forModule(CustomDirectoryStructurePanel.class).get("zipFileLocationPreference", ""));
        // or:
        // someTextField.setText(SomeSystemOption.getDefault().getSomeStringProperty());
    }

    void store() {
        // TODO store modified settings
        // Example:
        // Preferences.userNodeForPackage(CustomDirectoryStructurePanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or for org.openide.util with API spec. version >= 7.4:
        NbPreferences.forModule(CustomDirectoryStructurePanel.class).put("zipFileLocationPreference", zipFileLocation.getText());
        // or:
        // SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField zipFileLocation;
    private javax.swing.JButton zipFileLocationButton;
    private javax.swing.JFileChooser zipFileLocationChooser;
    private javax.swing.JLabel zipFileLocationLabel;
    // End of variables declaration//GEN-END:variables
}
