/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chasenoel.directorystructuretemplates;

import javax.swing.JPanel;

public final class NewDirectoryStructureVisualPanel extends JPanel {

    /**
     * Creates new form BuildCustomDirectoryStructureVisualPanel1
     */
    public NewDirectoryStructureVisualPanel() {
        initComponents();
    }
    
    static final String FOLDER_NAME = "NewFolder";
    
    public String getFolderName()
    {
        return folderName.getText();
    }
    
    @Override
    public String getName() {
        return "Folder Name";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newFolderPanel = new javax.swing.JPanel();
        folderNameLabel = new javax.swing.JLabel();
        folderName = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(folderNameLabel, org.openide.util.NbBundle.getMessage(NewDirectoryStructureVisualPanel.class, "NewDirectoryStructureVisualPanel.folderNameLabel.text")); // NOI18N

        folderName.setText(org.openide.util.NbBundle.getMessage(NewDirectoryStructureVisualPanel.class, "NewDirectoryStructureVisualPanel.folderName.text")); // NOI18N

        javax.swing.GroupLayout newFolderPanelLayout = new javax.swing.GroupLayout(newFolderPanel);
        newFolderPanel.setLayout(newFolderPanelLayout);
        newFolderPanelLayout.setHorizontalGroup(
            newFolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newFolderPanelLayout.createSequentialGroup()
                .addComponent(folderNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(folderName, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 365, Short.MAX_VALUE))
        );
        newFolderPanelLayout.setVerticalGroup(
            newFolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newFolderPanelLayout.createSequentialGroup()
                .addGroup(newFolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(folderNameLabel)
                    .addComponent(folderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newFolderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(newFolderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 185, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField folderName;
    private javax.swing.JLabel folderNameLabel;
    private javax.swing.JPanel newFolderPanel;
    // End of variables declaration//GEN-END:variables
}

